Shifty/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^core/', include('core.urls')),
    url(r'^menu/', include('menu.urls')),
    url(r'', include('log.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.USE_TOOLBAR and settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

admin.site.site_header = 'Shifty Administration'

log/urls.py
from django.conf.urls import url

from log.forms import LoginForm

from django.contrib.auth import views as django_views
from log import views as log_views
from log.views import HealthCheckCustomView
from . import views

urlpatterns = [

    # url(r'^home/$', views.home, name='real_home'),
    url(r'^$', views.home_or_login, name='home'),
    url(r'^login_success$', views.login_success, name='login_success'),
    url(r'^login/$', django_views.login, {'template_name': 'login.html',
                                          'authentication_form': LoginForm, 'redirect_authenticated_user': True},
        name='login'),
    url(r'^ht/$', HealthCheckCustomView.as_view()),
    url(r'^register/$', log_views.register, name='register'),
    url(r'^success/$', views.success, name='success'),
    url(r'^logout/$', django_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^edit_profile_form/$', views.edit_profile_form, name='edit_profile_form'),
    url(r'^ask_join/$', views.ask_join_business, name='ask_join_business'),
    # -------------- Manager section ------------------------ #

    url(r'^manager/$', views.manager_home, name='manager_home'),
    url(r'^manager/logout/$', django_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^manager/edit_business/$', views.edit_business, name='edit_business'),
    url(r'^manager/add_employees/$', views.add_employees, name='add_employees'),
    url(r'^manager/manage_employees/$', views.manage_employees, name='manage_employees'),
    url(r'^manager/delete_user/$', views.delete_user, name='delete_user'),

    # -------------- Employee section ------------------------ #

    url(r'^employee/$', views.emp_home, name='emp_home'),
]

log/models.py
from __future__ import unicode_literals, division

import json
import urllib2
from datetime import datetime
from urlparse import urlparse

import logging

from django.conf import settings
from django.core.cache import cache
from django.core.files.base import ContentFile
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Prefetch
from django.db.models.signals import post_save
from django.dispatch import receiver

from core.date_utils import get_curr_week_num
from log.utils import generate_password

logger = logging.getLogger(__name__)


class Business(models.Model):
    business_name = models.CharField(primary_key=True, max_length=30)

    manager = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    BUSINESS_TYPE_CHOICES = (
        ('RE', 'Restaurant'), ('CA', 'Cafe'), ('PU', 'Pub')
    )
    business_type = models.CharField(
        max_length=2,
        choices=BUSINESS_TYPE_CHOICES,
        default='CA',
    )

    address = models.CharField(max_length=30, blank=True, null=True)

    logo = models.ImageField(upload_to='logos/', null=True, blank=True)

    TIP_METHOD_CHOICES = (
        ('P', 'Personal'), ('G', 'Group')
    )

    tip_method = models.CharField(max_length=1, choices=TIP_METHOD_CHOICES, default='G')

    DAYS_OF_WEEK = (
        ('1', 'Sunday'),
        ('2', 'Monday'),
        ('3', 'Tuesday'),
        ('4', 'Wednesday'),
        ('5', 'Thursday'),
        ('6', 'Friday'),
        ('7', 'Saturday'),
    )
    deadline_day = models.CharField(max_length=1, choices=DAYS_OF_WEEK, default='7')
    slot_request_enabled = models.BooleanField(default=False)

    SHIFT_GENERATION_STATUS = (
        ('0', 'Not generated'),
        ('1', 'Generated'),
        ('2', 'Failed'),
        ('3', 'Generating')
    )
    shifts_generated = models.CharField(max_length=1, choices=SHIFT_GENERATION_STATUS, default='0')

    def __str__(self):
        return self.business_name

    def get_type(self):
        return self.get_business_type_display()

    def get_employees(self):
        return self.employeeprofile_set.all().prefetch_related('user')

    def get_role_employees(self, role):
        return self.get_employees().filter(role=EmployeeProfile.get_roles_reversed()[role.title()])

    def get_waiters(self):
        return self.get_role_employees('waiter')

    def get_bartenders(self):
        return self.get_role_employees('bartender')

    def get_cooks(self):
        return self.get_role_employees('cook')

    def get_manager(self):
        return self.get_role_employees('manager').first()

    def has_deadline_day_passed(self):
        today_weekday = datetime.today().weekday() + 2
        today_weekday = 1 if today_weekday == 8 else today_weekday
        today_weekday = 2 if today_weekday == 9 else today_weekday

        return today_weekday >= int(self.deadline_day)

    def set_shift_generation_success(self):
        self.shifts_generated = '1'

    def set_shift_generation_failure(self):
        self.shifts_generated = '2'

    def set_shift_generation_pending(self):
        self.shifts_generated = '3'

    def reset_shift_generation_status(self):
        self.shifts_generated = '0'

    def save_logo_from_url(self, url):
        name = urlparse(url).path.split('/')[-1]
        content = ContentFile(urllib2.urlopen(url).read())
        self.logo.save(name, content, save=False)

    def get_next_week_slots_cache_key(self, week):
        return "next-week-slots-{0}-{1}".format(self, week)

    def get_cached_next_week_slots(self, week):
        from core.models import ShiftSlot
        key = self.get_next_week_slots_cache_key(week)
        if key not in cache:
            slots = ShiftSlot.objects.filter(week=week, business=self, is_mandatory=False)
            cache.set(key, slots, settings.DURATION_CACHE_TTL)
            logger.debug('getting next week slots from DB')
            return slots
        logger.debug('getting next week slots from cache')
        return cache.get(key)

    def get_slot_names_cache_key(self):
        return "{0}-slot-names".format(self)

    def get_leaders_cache_key(self):
        return "{0}-leaders".format(self)

    def get_previous_shifts(self):
        from core.models import Shift
        key = self.get_prev_shifts_cache_key()
        if key not in cache:
            logger.info('getting previous shifts for business %s from DB', self)
            prev_shifts = Shift.objects.filter(slot__week__lt=get_curr_week_num(), slot__business=self) \
                .order_by('-slot__week', '-slot__day', '-slot__start_hour') \
                .select_related('slot').prefetch_related(Prefetch('employees',
                                                                  queryset=EmployeeProfile.objects.select_related(
                                                                      'user')))
            cache.set(key, prev_shifts)
        else:
            logger.info('getting previous shifts for business %s from cache', self)
            prev_shifts = cache.get(key)

        return prev_shifts

    def get_prev_shifts_cache_key(self):
        return "{0}-prev-shifts".format(self)

    def flush_prev_shifts_cache(self):
        logger.debug('flushing cache of prev shifts of business %s...', self)
        cache.delete(self.get_prev_shifts_cache_key())


class EmployeeProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', primary_key=False)
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    phone_regex = RegexValidator(regex=r'^05\d{1}-\d{7}$',
                                 message="Wrong phone number format.")
    phone_num = models.CharField(validators=[phone_regex], blank=True, max_length=16)  # validators should be a list
    home_address = models.CharField(max_length=30, blank=True, null=True)
    birth_date = models.DateField(null=True, blank=True)
    started_work_date = models.DateField(null=True, blank=True)

    GENDER_CHOICES = (
        ('M', 'Male'), ('F', 'Female')
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='M')

    ROLE_CHOICES = (
        ('MA', 'Manager'), ('WA', 'Waiter'), ('BT', 'Bartender'), ('CO', 'Cook')
    )

    rate = models.FloatField(default=0)

    role = models.CharField(
        max_length=2,
        choices=ROLE_CHOICES,
        default='WA',
    )
    enable_mailing = models.BooleanField(default=True)
    menu_score = models.IntegerField(null=True, blank=True)

    ever_logged_in = models.BooleanField(default=False)
    ARRIVAL_METHOD_CHOICES = (
        ('D', 'driving'), ('W', 'walking'), ('B', 'both')
    )
    arriving_method = models.CharField(max_length=1, choices=ARRIVAL_METHOD_CHOICES, default='D')
    new_messages = models.IntegerField(default=0)
    preferred_shift_time_frames = models.TextField(blank=True, null=True)
    credentials_sent = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    # noinspection PyTypeChecker
    def get_employment_months(self):
        if self.started_work_date:
            today = datetime.now().date()
            delta = today - self.started_work_date
            return round(delta.days / 30, 1)
        return None

    def get_age(self):
        if self.birth_date:
            today = datetime.now().date()
            delta = today - self.birth_date
            return round(delta.days / 365, 2)
        return None

    def get_manager(self):
        profile_business = self.business
        for profile in profile_business.employeeprofile_set.all():
            if profile.role == 'MA':
                return profile
        return None

    def get_manager_user(self):
        if self.get_manager():
            return self.get_manager().user

    def get_manger_msgs_of_employee(self, is_new):
        from core.models import ManagerMessage
        if is_new:
            messages = ManagerMessage.objects.filter(
                recipients__in=[self]).order_by('-sent_time')[:self.new_messages]
            return messages

        key = self.get_old_manager_msgs_cache_key()
        if key not in cache:
            messages = ManagerMessage.objects.filter(
                recipients__in=[self]).order_by('-sent_time')[self.new_messages:]
            cache.set(key, list(messages), settings.DURATION_CACHE_TTL)
            logger.debug('Taking old manager messages from DB: %s', messages)
            return messages
        logger.debug('Taking old manager messages from cache')
        return cache.get(key)

    def send_mail_to_manager(self):
        from Shifty.utils import send_multiple_mails_with_html
        send_multiple_mails_with_html(subject='New message in Shifty app',
                                      text='you\'ve got new message from %s' % self.user.username,
                                      template='html_msgs/new_employee_change_request.html',
                                      r_2_c_dict={self.get_manager_user():
                                                      {'employee_first_name': self.user.first_name,
                                                       'employee_last_name': self.user.last_name}})

    def flush_new_messages(self):
        if self.new_messages > 0:
            logger.debug('flushing cache of old manager msgs of emp %s', self)
            cache.delete(self.get_old_manager_msgs_cache_key())
        self.new_messages = 0
        self.save()

    def flush_swap_requests_cache(self):
        logger.debug('flushing cache of old swap requests of emp %s', self)
        cache.delete(self.get_old_swap_requests_cache_key())

    def get_old_manager_msgs_cache_key(self):
        if self.role == 'MA':
            raise ValueError('Can\'t get manager messages key of emp %s - is manager' % self)
        return "{0}-old-manager-messages".format(self)

    def get_old_swap_requests_cache_key(self):

templates/manager/addEmployees.html
{% extends 'manager/base.html' %}

{% block title %}
<title>Shifty Bitch</title>
{% endblock %}

{% block comp_name %}
    <i>{{ user.profile.business.business_name }}</i> dashboard
{% endblock %}

{% block content %}

<div class="container">
	<div class="row text-center">
        <div class="col-sm-6 col-sm-offset-3">
        <br><br> <h2 style="color:#0fad00">Success</h2>
        <img src="http://osmhotels.com//assets/check-true.jpg">
        <h3>Dear, {{ user.username }}</h3>
        <p style="font-size:20px;color:#5C5C5C;">Thank you for registering <i>{{ user.profile.business }}</i> to Shifty.
        It's time to add your employees :)</p>
        <a href="" class="btn btn-success">     Add employees      </a>
    <br><br>
        </div>

	</div>
</div>

{% endblock %}

templates/manager/add_employees.html
{% extends 'manager/base.html' %}
{% load staticfiles %}

{% block title %}
    <title>Add Employees</title>
{% endblock %}

{% block comp_name%}
{{ user.profile.business }}
{% endblock %}

{% block content %}


    {% if next %}
        {% if user.is_authenticated %}
            <p>Your account doesn't have access to this page. To proceed,
                please login with an account that has access.</p>
        {% else %}
            <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }} (field name: {{ field.name }})</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <div class="container">
        <div class="row" style="margin-bottom: 30px">
            <div class="col-xs-6 col-xs-offset-4">
                <h2>Add Employees to {{ user.profile.business }}</h2>
            </div>
        </div>
        <div class="row" style="margin-bottom: 30px">
            <div class="col-xs-12 col-xs-offset-2">
                <ol>
                    <li>First, Users will be created in the system for your employees.</li>
                    <li>Second, emails will be sent to them with their credentials so they will be able to login.</li>
                </ol>
{#                <p>First, Users will be created in the system for your employees.#}
{#                Second, emails will be sent to them with their credentials so they will be able to login.</p>#}
            </div>
        </div>
        <div class="row">
            <form action="." id="bookForm" method="post" class="form-horizontal">
                {% csrf_token %}
                <div class="form-group">
                    <div class="col-xs-2">
                        <input type="text" class="form-control" name="employee_0_firstName" placeholder="First Name" />
                    </div>
                    <div class="col-xs-2">
                        <input type="text" class="form-control" name="employee_0_lastName" placeholder="Last Name" />
                    </div>
                    <div class="col-xs-3">
                        <input type="email" class="form-control" name="employee_0_email" placeholder="Email" />
                    </div>
                    <div class="col-xs-2">
                        <select name="employee_0_role" class="form-control">
                              <option value="" disabled selected>Employee role</option>
                              <option value="WA">Waiter</option>
                              <option value="BT">Bartender</option>
                              <option value="CO">Cook</option>
                        </select>
                    </div>
                    <div class="col-xs-2">
                        <input type="date" name="employee_0_dateJoined" class="dateclass placeholderclass form-control"
                               placeholder="Date started"
                               onClick="$(this).removeClass('placeholderclass')">
                    </div>
                    <div class="col-xs-1">
                        <button type="button" class="btn btn-info addButton"><span class="glyphicon glyphicon-plus"></span>
                        </button>
                    </div>
                </div>

                <div class="form-group submit-group" style="margin-top: 30px">
                    <div class="col-xs-5 col-xs-offset-5">
                        <button type="submit" class="btn btn-lg btn-success btn-submit"
                                data-loading-text="<i class='fa fa-spinner fa-spin '></i> Processing Request">
                            Submit</button>
                    </div>
                </div>
                <div class="progress" style="display: none">
                  <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuemin="0"
                       aria-valuemax="100" style="width: 0%;">
                    <span class="sr-only"></span>
                      Creating <span id="percent"></span>
                  </div>
                </div>

            </form>


                <!-- The template for adding new field -->
                 <div class="form-group hide" id="employeeTemplate">
                    <div class="col-xs-2">
                        <input type="text" class="form-control" name="firstName" placeholder="First Name" />
                    </div>
                    <div class="col-xs-2">
                        <input type="text" class="form-control" name="lastName" placeholder="Last Name" />
                    </div>
                    <div class="col-xs-3">
                        <input type="email" class="form-control" name="email" placeholder="Email" />
                    </div>
                     <div class="col-xs-2">
                        <select name="role" class="form-control" id="role_select">
                              <option value="WA">Waiter</option>
                              <option value="BT">Bartender</option>
                              <option value="CO">Cook</option>
                        </select>
                    </div>
                    <div class="col-xs-2">
                        <input type="date" name="date" class="dateclass placeholderclass form-control"
                               placeholder="Date started"
                               onClick="$(this).removeClass('placeholderclass')">
                    </div>
                    <div class="col-xs-1">
                        <button type="button" class="btn btn-danger removeButton">
                            <span class="glyphicon glyphicon-minus"></span>
                        </button>
                    </div>
                </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
    <script src="{% static 'js/add_employees.js' %}" type="text/javascript"></script>
{% endblock %}

templates/manager/edit_business.html
{% extends "manager/base.html" %}

{% block title %}
<title>Edit business</title>
{% endblock %}

{% block comp_name %}
{{ user.profile.business }}
{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="login-panel panel panel-default">
                <div class="panel-heading head-custom">
                    <h3 class="panel-title" style="display: inline">Edit {{ user.profile.business }} details</h3>
                    <a href="{% url 'home' %}" style="float: right">Back to dashboard</a>
                </div>
                <div class="panel-body" >
                    <form action="." method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                    {{ business_form.as_p }}
                    <hr>
                    <div class="text-center">
                    <input type="submit" class="btn btn-info btn-lg" value="Submit">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}

    <script>
        $(document).ready(function () {
            $( ".helptext" ).wrap( "<small></small>" );
        });
    </script>

{% endblock %}

templates/manager/emp_requests.html
{% if requests %}
    {% for request in requests %}
        <div class="row" style="margin-top: 20px">
        <div class="col-xs-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title" style="display: inline">{{ request.subject }}</h3>
                    <span style="float: right">From: {{ request.get_issuers_string }}</span>
                </div>
                <div class="panel-body">
                    {{ request.text }}
                </div>
                {% if is_pending %}
                    <div class="panel-footer">
                        <span class="hidden-id" style="visibility: hidden">{{ request.id }}</span>
                        <span class="timestamp"> {{ request.sent_time }} </span>
                        <div style="float: right">
                            <button type="button" class="btn btn-xs btn-success approve"><span
                                    class="glyphicon glyphicon-ok-sign"></span> Approve
                            </button>
                            <button type="button" class="btn btn-xs btn-danger reject"><span
                                    class="glyphicon glyphicon-remove"></span> Reject
                            </button>
                            <i class="fa fa-spinner fa-spin"
                               style="font-size:18px; margin-left: 10px; display: none"></i>
                        </div>
                    </div>
                {% else %}
                    {% if request.status == 'A' %}
                        <div class="panel-footer approved">
                    {% else %}
                        <div class="panel-footer rejected">
                    {% endif %}
                    <span class="hidden-id" style="visibility: hidden">{{ request.id }}</span>
                    <span class="timestamp"> {{ request.sent_time }} </span>
                    <div style="float: right">
                        <span>{{ request.get_status_display }}</span>
                    </div>
                    </div>
                    </div>
                {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
{% else %}
<div style="text-align: center; margin-top: 20px">
    {% if is_pending %}
        No pending requests found
    {% else %}
        No closed requests found
    {% endif %}
</div>
{% endif %}

templates/manager/es_shifts.html
{% for shift in shifts %}
    <div class="row" style="margin-top: 10px">
        <div class="col-xs-5 col-xs-offset-3">
            <div class="panel panel-default" style="text-align: center">
                <div class="panel-heading">
                    <h3 class="panel-title" style="display: inline">
                        {{ shift.body.name}} - {{ shift.body.date }}
                    </h3>
                </div>
                <div class="panel-body">
                    {{ shift.body.employees.employees }}
                    <hr>
                    {% autoescape off %}
                    {{ shift.highlights }}
                    {% endautoescape %}
                </div>
                <div class="panel-footer">
                    Elastic-Search score: <strong>{{ shift.score }}</strong>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

templates/manager/new_employee_email_msg.html
<h2>{{ first_name }}, welcome to Shifty !</h2>

<p>You have been added by your manager, {{ manager }}, to the business {{ business }} as a {{ role }}</p>

<p>Your credentials are:</p><br>

<ul>
    <li>username: {{ username }}</li>
    <li>password: {{ password }}</li>
</ul>

<p>go to <a href="http://localhost:8000">Shifty website</a> and enjoy !</p>

templates/manager/register.html
{% extends "manager/base.html" %}

{% block title %}
    <title>Register nw business</title>
{% endblock %}

{% block style %}
    <style>
        a.my-tool-tip, a.my-tool-tip:hover, a.my-tool-tip:visited {
            color: black;
            margin-left: 10px;
        }
{#        input[name='logo'], label[for='id_logo'] {#}
{#            display: none;#}
{#        }#}
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title" style="display: inline">Register yor business to Shifty</h3>
                        <a href="/login" style="float: right">Already registered?</a>
                    </div>
                    <div class="panel-body">
                        <form action="." method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <h4 style="text-align: center">Manager Details</h4>
                            {{ manager_form.as_p }}
                            <hr>
                            <h4 style="text-align: center">Business Details</h4>
                            {{ business_form.as_p }}
                            <hr>
                            <div class="text-center">
                                <input type="submit" class="btn btn-info btn-lg" value="Submit">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" role="dialog" aria-hidden="true" id="suggestionModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Business logo</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Is this your business logo?</p>
                    <img id="myImage" src="" alt="">
                </div>
                <div class="modal-footer">
                    <button id="yesLogo" class="btn btn-primary" data-dismiss="modal">Yes, amazing!</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Nope</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        $(document).ready(function () {
            var tooltip_desc = "How your employees get their tip? Whether individually or get a portion from grouped amount";
            $("label[for='id_tip_method']").after('<a class="my-tool-tip" data-toggle="tooltip" data-placement="right" title="' + tooltip_desc + '">' +
                '<i class="glyphicon glyphicon-info-sign"></i> </a>');
            $("a.my-tool-tip").tooltip();

            $("input[name='business_name']").blur(showSuggestion);

            $("#yesLogo").click(saveLink);

            function showSuggestion() {
                var name = $("input[name='business_name']").val();
                $.ajax({
                    url: "{% url 'logo_suggestion' %}" +"?name=" + name,
                    type: "get",
                    success: popSuggestionModal,
                    error:   showLogoInput
                });
            }

            function popSuggestionModal(res) {
                $("input[name='logo']").hide();
                $("label[for='id_logo']").hide();
                var url = res['logo_url'];
                $('#myImage').attr('src', url);

                $('#suggestionModal').modal('show');
            }
            function showLogoInput(xhr) {
                console.error(xhr.responseText);
            }
            function saveLink() {
                var imageSrc = $("#myImage").attr('src');
                $("input[name='logo_url").val(imageSrc);
                console.log($("input[name='logo_url").val());
            }
        })
    </script>
{% endblock %}

templates/manager/register_success.html
{% extends 'manager/base.html' %}
{% load static %}

{% block title %}
<title>Shifty Bitch</title>
{% endblock %}

{% block comp_name %}
    <i>{{ user.profile.business.business_name }}</i> dashboard
{% endblock %}

{% block content %}

<div class="container">
	<div class="row text-center">
        <div class="col-sm-6 col-sm-offset-3">
        <br><br> <h2 style="color:#0fad00">Success</h2>
        <img src="{% static  "imgs/success.png" %}" width="140px" height="100px">
        <h3>Dear {{ user.username }}</h3>
        <p style="font-size:20px;color:#5C5C5C;">Thank you for registering <i>{{ user.profile.business }}</i> to Shifty.<br>
        It's time to add your employees =)</p><br>
        <a href="{% url 'add_employees' %}" class="btn btn-success">     Add employees      </a><br><br>
        <a href="{% url 'home' %}">     Skip to dashboard      </a>
    <br><br>
        </div>

	</div>
</div>

{% endblock %}

templates/manager/shift_summary_form.html
<form method="post" action={% url 'submit_shift_summary' slot_id%}>
    {% csrf_token %}
    {% if summary_form.errors %}
        {% for err in summary_form.errors %}
                    <div class="alert alert-danger">
                <strong>{{ err }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    {{ summary_form.as_p }}
    <button class="btn btn-primary" type="submit">Submit</button>
</form>

templates/manager/slot_request_emp_list.html
{% if emps|length > 0 %}
    <ul class="list-group" style="text-align: center">
        {% for emp in emps %}
            {% if emp == curr_emp %}
                <li class="list-group-item list-group-item-success">{{ emp.get_role_display }}: <strong>YOU</strong>
                </li>
            {% else %}
                <li class="list-group-item list-group-item-info">
                    {{ emp.get_role_display }}: <span class="username">{{ emp }}</span>
                    {% if emp.role == user.profile.role and offer_swap %}
                        <div>
                            <select>
                                <option value="" selected disabled>Select Shift</option>
                                {% for shift in future_shifts %}
                                    <option value="{{ shift.id }}">{{ shift.shift }}</option>
                                {% endfor %}
                            </select>
                            <button class="btn-info btn-xs swapBtn">Request for swap</button>
                        </div>
                        </li>
                    {% endif %}
            {% endif %}
        {% endfor %}
    </ul>
{% else %}
    {{ empty_msg }}
{% endif %}